### ISSUE TITLE
Support for Liferay 7 CE GA4

### ISSUE THREAD

**Issue by vpsalcedos** [amusarra/liferay-portal-sqlserverdb-support#2] opened 2017-09-27 14:54 UTC
Do you now if this solution supports liferay 7 GA4, I have encounter a problem while restarting tomcat.

**Comment by amusarra** [comment] 2017-09-27 16:27
I tested the driver up to GA3. Could you tell me the stacktrace of the error?

**Comment by vpsalcedos** [comment] 2017-09-27 16:34
Here it is...
[liferay_log_sqlsever.txt](https://github.com/amusarra/liferay-portal-sqlserverdb-support/files/1337975/liferay_log_sqlsever.txt)

**Comment by amusarra** [comment] 2017-09-27 16:51
Are you sure you have set up the database connection parameters correctly? What you sent me and a thread dump send me the liferay.log.

**Comment by amusarra** [comment] 2017-09-27 19:58
@vpsalcedos Which version of the SQL Server you are using?

**Comment by vpsalcedos** [comment] 2017-09-27 20:42
SQL Server 2014

**Comment by amusarra** [comment] 2017-09-27 21:19
I just did a test with SQL Express 2014 and did not encounter any problem on the database.
On log files I did not encounter any SQL exception. I've also created some complex web content with no problem. Can you be more accurate about the error you get from the database?

![schermata 2017-09-27 alle 22 58 35](https://user-images.githubusercontent.com/708110/30938283-cd9d8314-a3d9-11e7-8513-44dc1f292e34.png)
![schermata 2017-09-27 alle 23 16 17](https://user-images.githubusercontent.com/708110/30938317-e912e120-a3d9-11e7-8048-dc75a6a86e7e.png)

**Comment by vpsalcedos** [comment] 2017-09-27 22:17
Thank you for your time.

Using Liferay 7 GA4 with tomcat, I configured the connection with my SQL Server 2014 database. When I finished the wizard it demands to restart the server. When restarting the server I could see that database was populated with liferay tables, however the server could not started and I get the error I sent you (I don't know how to get access to the hole log). In the error I can see a problem with jdbc connection.

Can you please help me?

**Comment by amusarra** [comment] 2017-09-27 22:26
Stop Liferay, on your portal-setup-wizard.properties add this lines and review data for db connection. Restart Liferay.

```
setup.wizard.enabled=false

##
## JDBC
##

    #
    # SQL Server
    #
    jdbc.default.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc.default.username=$DB_USER_NAME$
    jdbc.default.password=$DB_USER_PASSWORD$
    jdbc.default.url=jdbc:sqlserver://$SQL_SERVER_IP;databaseName=$DB_NAME$
```

**Comment by amusarra** [comment] 2017-09-27 23:17
I tried to replicate your case by enabling the Setup Wizard, but I did not get any errors even after the reboot. I also uploaded sample data. Try sending log files $LIFERAY_HOME/tomcat-8.0.32/logs/catalina.out and the last log in side $LIFERAY_HOME/logs/

![schermata 2017-09-28 alle 00 57 09](https://user-images.githubusercontent.com/708110/30942238-1b1094a0-a3ea-11e7-9d78-3d8428d0ee23.png)
![schermata 2017-09-28 alle 00 56 22](https://user-images.githubusercontent.com/708110/30942237-1b0c195c-a3ea-11e7-9ae5-22a1f73e5c02.png)

**Comment by vpsalcedos** [comment] 2017-09-27 23:31
Hello,

This is what I have:
![screen shot 2017-09-27 at 6 28 28 pm](https://user-images.githubusercontent.com/5255203/30942664-c6d59d3c-a3b1-11e7-9cc2-9e7c58ece0ad.png)

[liferay.2017-09-27.log](https://github.com/amusarra/liferay-portal-sqlserverdb-support/files/1338989/liferay.2017-09-27.log)

**Comment by vpsalcedos** [comment] 2017-09-27 23:40
Have you restart liferay after getting the successful message. My problem is after restarting.

**Comment by amusarra** [comment] 2017-09-28 13:38
I can not replicate your problem. I do not think the problem is due to the SQL Server driver. I recommend you get started again. Download the GA4 and install it on a more standard path (/opt/...). I have no problems even after rebooting.

**Comment by vpsalcedos** [comment] 2017-09-28 18:15
Thank you for your help.

I think the problem is because the database is in a different server.

**Comment by amusarra** [comment] 2017-09-28 19:11
@vpsalcedos That's not the problem. It's a normal situation for the database to be on another server. Also in my case Liferay and SQL Server are on different servers.

**Comment by amusarra** [comment] 2017-09-29 08:08
Hi @vpsalcedos Any news? I must close this issue because I not be able to replicate your issue.

**Closed** 2017-09-29 17:31 UTC
